import io
import logging
from pathlib import Path
from fpdf import FPDF
import matplotlib.pyplot as plt
from typing import Dict, Any


class PDF(FPDF):
    """
    Custom PDF class for generating the respiratory waveform analysis report.
    """

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 10, "Respiratory Waveform Analysis Report", 0, 1, "C")

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "C")

    def chapter_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 10, title, 0, 1, "L")
        self.ln(5)

    def chapter_body(self, body_text: str, image_data: io.BytesIO = None):
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 5, body_text)
        self.ln()
        if image_data:
            self.image(image_data, x=10, w=self.w - 20)
            self.ln()


def create_report(case_id: str, paths: Dict[str, str], data: Dict[str, Any]):
    """
    Generates a PDF report summarizing the respiratory analysis findings.

    Args:
        case_id (str): The patient case ID.
        paths (Dict[str, str]): Output directories dictionary.
        data (Dict[str, Any]): All collected data, waveforms, correlations, and settings.
    """
    report_path = Path(paths["report"]) / f"{case_id}_report.pdf"
    plot_data = {}
    winning_ap_method, winning_lat_method = data["winning_methods"]

    for view in ["ap", "lat"]:
        buf = io.BytesIO()
        plt.figure(figsize=(8, 8))
        plt.imshow(data[f"{view}_roi_viz"])
        plt.title(f"{view.upper()} Lung ROI")
        plt.axis("off")
        plt.savefig(buf, format="png", bbox_inches="tight")
        plt.close()
        buf.seek(0)
        plot_data[f"{view}_roi_viz"] = buf

    for view in ["ap", "lat"]:
        for method in ["centroid", "roi_pca"]:
            buf = io.BytesIO()
            plt.figure(figsize=(12, 4))
            plt.plot(data[f"{view}_{method}_raw"], label="Raw", alpha=0.5)
            plt.plot(data[f"{view}_{method}_filtered"], label="Filtered", linewidth=2)

            winning_method = winning_ap_method if view == "ap" else winning_lat_method
            if method == winning_method:
                start, end, name, cycle_type = data[f"{view}_cycle"]
                plt.axvspan(
                    start, end, color="red", alpha=0.2, label=f"Best Cycle ({name})"
                )

            plt.title(
                f"Case {case_id} - {view.upper()} Respiratory Waveform ({method.upper()})"
            )
            plt.xlabel("Frame Number")
            plt.ylabel("Signal Amplitude")
            plt.legend()
            plt.grid(True)

            plt.savefig(buf, format="png", bbox_inches="tight")
            plt.close()
            buf.seek(0)
            plot_data[f"{view}_{method}"] = buf

    pdf = PDF()
    pdf.add_page()

    pdf.chapter_title(f"Analysis Summary for Case: {case_id}")
    summary_text = (
        f"The best matching cycle pair was found between AP ({winning_ap_method.upper()}) "
        f"and LAT ({winning_lat_method.upper()}) with a Pearson correlation of {data['max_corr']:.4f}."
    )
    pdf.chapter_body(summary_text)

    pdf.chapter_title("1. Lung Field Detection (ROI)")
    pdf.chapter_body(
        "The following masks were generated by the U-Net model and used as the ROI for the ROI-PCA method.",
        image_data=plot_data["ap_roi_viz"],
    )
    pdf.chapter_body("", image_data=plot_data["lat_roi_viz"])

    pdf.chapter_title("2. AP Waveform Analysis")
    pdf.chapter_body(
        "2-A: CENTROID Method Waveform.", image_data=plot_data["ap_centroid"]
    )
    pdf.chapter_body(
        "2-B: ROI-PCA Method Waveform.", image_data=plot_data["ap_roi_pca"]
    )

    pdf.chapter_title("3. LAT Waveform Analysis")
    pdf.chapter_body(
        "3-A: CENTROID Method Waveform.", image_data=plot_data["lat_centroid"]
    )
    pdf.chapter_body(
        "3-B: ROI-PCA Method Waveform.", image_data=plot_data["lat_roi_pca"]
    )

    pdf.chapter_title("4. Correlation Summary Table")
    pdf.set_font("Helvetica", "B", 10)
    line_height = pdf.font_size * 1.5
    col_widths = (pdf.epw * 0.3, pdf.epw * 0.3, pdf.epw * 0.4)

    pdf.cell(col_widths[0], line_height, "AP Method", border=1, align="C")
    pdf.cell(col_widths[1], line_height, "LAT Method", border=1, align="C")
    pdf.cell(col_widths[2], line_height, "Highest Correlation", border=1, align="C")
    pdf.ln(line_height)

    pdf.set_font("Helvetica", "", 10)
    for methods, corr in data["all_results"].items():
        pdf.cell(col_widths[0], line_height, methods[0].upper(), border=1)
        pdf.cell(col_widths[1], line_height, methods[1].upper(), border=1)
        pdf.cell(col_widths[2], line_height, f"{corr:.4f}", border=1, align="C")
        pdf.ln(line_height)

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0,
        10,
        f"Total execution time: {data['execution_time']:.2f}s. Detailed CSV logs in report/csv_details.",
    )

    pdf.output(str(report_path))
    logging.info(f"Created PDF report: {report_path}")
